version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 20
    ignore:
    # TEMPORARY: Ignore minitest 6.x until Rails >= 8.1
    # Remove this rule when upgrading Rails.
    - dependency-name: "minitest"
      versions: [ ">=6.0.0" ]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Ruby needs to be upgraded manually in multiple places, so cannot
  # be upgraded by Dependabot. That effectively makes the below
  # config redundant, as ruby is the only updatable thing in the
  # Dockerfile, although this may change in the future. We hope this
  # config will save a dev from trying to upgrade ruby via Dependabot.
  - package-ecosystem: docker
    ignore:
      - dependency-name: ruby
    directory: /
    schedule:
      interval: weekly
