# Pact verify workflow
#
# This workflow asserts that Pact contract tests are valid against this
# codebase. It is trigged when changes are made to this project and it
# is explicitly called by GDS API Adapters when changes are made there.

name: Run Pact tests

on:
  workflow_call:
    inputs:
      # The commit / tag of this repo to test against
      ref:
        required: false
        type: string
        default: main
      # A GitHub Action artifact which contains the pact definition files
      # Publishing API calls this action to test new pacts against this
      # workflow
      pact_artifact:
        required: false
        type: string
      # When using an artifact this is the file path to the pact that is verified
      # against
      pact_artifact_file_to_verify:
        required: false
        type: string
        default: gds_api_adapters-signon_api.json
      # Which version of the pacts to use from the Pact Broker service
      # This option will be ignored if pact_artifact is set
      pact_consumer_version:
        required: false
        type: string
        default: branch-main

jobs:
  pact_verify:
    name: Verify pact tests
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Setup MySQL
        id: setup-mysql
        uses: alphagov/govuk-infrastructure/.github/actions/setup-mysql@main

      - name: Setup Redis
        uses: alphagov/govuk-infrastructure/.github/actions/setup-redis@main

      - uses: actions/checkout@v6
        with:
          repository: alphagov/signon
          ref: ${{ inputs.ref }}

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bundle exec rails db:setup
        env:
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}

      - if: inputs.pact_artifact == ''
        run: bundle exec rake pact:verify
        env:
          RAILS_ENV: test
          PACT_CONSUMER_VERSION: ${{ inputs.pact_consumer_version }}
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}

      - if: inputs.pact_artifact != ''
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.pact_artifact }}
          path: tmp/pacts

      - if: inputs.pact_artifact != ''
        run: ls -la tmp/pacts/

      - if: inputs.pact_artifact != ''
        run: |
          # shellcheck disable=SC2102
          bundle exec rake pact:verify:at[tmp/pacts/${{ inputs.pact_artifact_file_to_verify }}]
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: ${{ steps.setup-mysql.outputs.db-url }}
